const defaultTheme = require('tailwindcss/defaultTheme')

// /** @type {import('tailwindcss').Config} */
module.exports = {
  variants: {
    borderWidth: ["first", "responsive", "last", "hover", "focus"],
  },
  content: [
    './public/*.html',
    './app/helpers/**/*.rb',
    './app/builders/**/*.rb',
    './app/javascript/**/*.js',
    './app/views/**/*.{erb,haml,html,slim}',
    './app/components/**/*.{erb,haml,html,slim,rb}'
  ],
  darkMode: ["class", '[data-mode="dark"]'],
  theme: {
    extend: {
      backgroundImage: {
        "gradient-primary":
          "linear-gradient(to right, var(--tw-gradient-stops, var(--ui-gradient-primary-stops)))",
        "gradient-secondary":
          "linear-gradient(to right, var(--ui-gradient-secondary-stops))",
        "gradient-button-primary":
          "linear-gradient(145deg, var(--tw-gradient-stops, var(--ui-gradient-primary-stops)));",
        "gradient-primary-faded":
          "linear-gradient(to right, var(--colors-purplesAlpha-100), var(--colors-pinksAlpha-100))",
        unset: "unset",
      },
      colors: {
        purple: {
          DEFAULT: "var(--colors-purple-500)",
          50: "var(--colors-purple-50)",
          100: "var(--colors-purple-100)",
          200: "var(--colors-purple-200)",
          300: "var(--colors-purple-300)",
          400: "var(--colors-purple-400)",
          500: "var(--colors-purple-500)",
          600: "var(--colors-purple-600)",
          700: "var(--colors-purple-700)",
          800: "var(--colors-purple-800)",
          900: "var(--colors-purple-900)",
        },
        purplesAlpha: {
          50: "var(--colors-purplesAlpha-50)",
          100: "var(--colors-purplesAlpha-100)",
          200: "var(--colors-purplesAlpha-200)",
          300: "var(--colors-purplesAlpha-300)",
          400: "var(--colors-purplesAlpha-400)",
          500: "var(--colors-purplesAlpha-500)",
          600: "var(--colors-purplesAlpha-600)",
          700: "var(--colors-purplesAlpha-700)",
          800: "var(--colors-purplesAlpha-800)",
          900: "var(--colors-purplesAlpha-900)",
        },

        pink: {
          DEFAULT: "var(--colors-pink-500)",
          50: "var(--colors-pink-50)",
          100: "var(--colors-pink-100)",
          200: "var(--colors-pink-200)",
          300: "var(--colors-pink-300)",
          400: "var(--colors-pink-400)",
          500: "var(--colors-pink-500)",
          600: "var(--colors-pink-600)",
          700: "var(--colors-pink-700)",
          800: "var(--colors-pink-800)",
          900: "var(--colors-pink-900)",
        },
        pinksAlpha: {
          50: "var(--colors-pinksAlpha-50)",
          100: "var(--colors-pinksAlpha-100)",
          200: "var(--colors-pinksAlpha-200)",
          300: "var(--colors-pinksAlpha-300)",
          400: "var(--colors-pinksAlpha-400)",
          500: "var(--colors-pinksAlpha-500)",
          600: "var(--colors-pinksAlpha-600)",
          700: "var(--colors-pinksAlpha-700)",
          800: "var(--colors-pinksAlpha-800)",
          900: "var(--colors-pinksAlpha-900)",
        },
        whitesAlpha: {
          50: "var(--colors-whitesAlpha-50)",
          100: "var(--colors-whitesAlpha-100)",
          200: "var(--colors-whitesAlpha-200)",
          300: "var(--colors-whitesAlpha-300)",
          400: "var(--colors-whitesAlpha-400)",
          500: "var(--colors-whitesAlpha-500)",
          600: "var(--colors-whitesAlpha-600)",
          700: "var(--colors-whitesAlpha-700)",
          800: "var(--colors-whitesAlpha-800)",
          900: "var(--colors-whitesAlpha-900)",
        },
        blacksAlpha: {
          50: "var(--colors-blacksAlpha-50)",
          100: "var(--colors-blacksAlpha-100)",
          200: "var(--colors-blacksAlpha-200)",
          300: "var(--colors-blacksAlpha-300)",
          400: "var(--colors-blacksAlpha-400)",
          500: "var(--colors-blacksAlpha-500)",
          600: "var(--colors-blacksAlpha-600)",
          700: "var(--colors-blacksAlpha-700)",
          800: "var(--colors-blacksAlpha-800)",
          900: "var(--colors-blacksAlpha-900)",
        },
        bluesAlpha: {
          50: "var(--colors-bluesAlpha-50)",
          100: "var(--colors-bluesAlpha-100)",
          200: "var(--colors-bluesAlpha-200)",
          300: "var(--colors-bluesAlpha-300)",
          400: "var(--colors-bluesAlpha-400)",
          500: "var(--colors-bluesAlpha-500)",
          600: "var(--colors-bluesAlpha-600)",
          700: "var(--colors-bluesAlpha-700)",
          800: "var(--colors-bluesAlpha-800)",
          900: "var(--colors-bluesAlpha-900)",
        },
        greensAlpha: {
          50: "var(--colors-greensAlpha-50)",
          100: "var(--colors-greensAlpha-100)",
          200: "var(--colors-greensAlpha-200)",
          300: "var(--colors-greensAlpha-300)",
          400: "var(--colors-greensAlpha-400)",
          500: "var(--colors-greensAlpha-500)",
          600: "var(--colors-greensAlpha-600)",
          700: "var(--colors-greensAlpha-700)",
          800: "var(--colors-greensAlpha-800)",
          900: "var(--colors-greensAlpha-900)",
        },
        orangesAlpha: {
          50: "var(--colors-orangesAlpha-50)",
          100: "var(--colors-orangesAlpha-100)",
          200: "var(--colors-orangesAlpha-200)",
          300: "var(--colors-orangesAlpha-300)",
          400: "var(--colors-orangesAlpha-400)",
          500: "var(--colors-orangesAlpha-500)",
          600: "var(--colors-orangesAlpha-600)",
          700: "var(--colors-orangesAlpha-700)",
          800: "var(--colors-orangesAlpha-800)",
          900: "var(--colors-orangesAlpha-900)",
        },
        primary: {
          DEFAULT: "var(--colors-purple-500)",
          50: "var(--colors-primary-50)",
          100: "var(--colors-purple-100)",
          200: "var(--colors-purple-200)",
          300: "var(--colors-purple-300)",
          400: "var(--colors-purple-400)",
          500: "var(--colors-purple-500)",
          600: "var(--colors-purple-600)",
          700: "var(--colors-purple-700)",
          800: "var(--colors-purple-800)",
          900: "var(--colors-purple-900)",
        },
        secondary: {
          DEFAULT: "var(--colors-pink-500)",
          500: "var(--colors-pink-500)",
        },
        tertiary: {
          DEFAULT: "var(--colors-orange-500)",
          500: "var(--colors-orange-500)",
        },
        quaternary: {
          DEFAULT: "var(--colors-blue-500)",
          500: "var(--colors-blue-500)",
        },
        ui: {
          text: {
            DEFAULT: "var(--ui-text-primary)",
            primary: "var(--ui-text-primary)",
            secondary: "var(--ui-text-secondary)",
            tertiary: "var(--ui-text-tertiary)",
          },
          background: {
            DEFAULT: "var(--ui-background)",
            alt: "var(--ui-background-alt)",
          },
          divider: {
            DEFAULT: "var(--ui-divider)",
            strong: "var(--ui-divider-strong)",
            faded: "var(--ui-divider-faded)",
          },
        },
      },
      fontFamily: {
        sans: "var(--be-vietnam-pro-font)",
      },
      borderColor: {
        DEFAULT: "var(--ui-divider)",
      },
      typography: {
        default: {
          css: {
            "--tw-prose-body": "var(--ui-text-primary)",
            "--tw-prose-headings": "var(--ui-text-primary)",
            "--tw-prose-lead": "var(--ui-text-primary)",
            "--tw-prose-links": "var(--ui-text-primary)",
            "--tw-prose-bold": "var(--ui-text-primary)",
            "--tw-prose-counters": "var(--ui-text-primary)",
            "--tw-prose-bullets": "var(--ui-text-primary)",
            "--tw-prose-hr": "var(--ui-text-primary)",
            "--tw-prose-quotes": "var(--ui-text-primary)",
            "--tw-prose-quote-borders": "var(--ui-text-primary)",
            "--tw-prose-captions": "var(--ui-text-primary)",
            "--tw-prose-code": "var(--ui-text-primary)",
            "--tw-prose-pre-code": "var(--ui-text-primary)",
            "--tw-prose-pre-bg": "var(--ui-text-primary)",
            "--tw-prose-th-borders": "var(--ui-text-primary)",
            "--tw-prose-td-borders": "var(--ui-text-primary)",
            "--tw-prose-invert-body": "var(--ui-text-primary)",
            "--tw-prose-invert-headings": "var(--ui-text-primary)",
            "--tw-prose-invert-lead": "var(--ui-text-primary)",
            "--tw-prose-invert-links": "var(--ui-text-primary)",
            "--tw-prose-invert-bold": "var(--ui-text-primary)",
            "--tw-prose-invert-counters": "var(--ui-text-primary)",
            "--tw-prose-invert-bullets": "var(--ui-text-primary)",
            "--tw-prose-invert-hr": "var(--ui-text-primary)",
            "--tw-prose-invert-quotes": "var(--ui-text-primary)",
            "--tw-prose-invert-quote-borders": "var(--ui-text-primary)",
            "--tw-prose-invert-captions": "var(--ui-text-primary)",
            "--tw-prose-invert-code": "var(--ui-text-primary)",
            "--tw-prose-invert-pre-code": "var(--ui-text-primary)",
            "--tw-prose-invert-pre-bg": "rgb(0 0 0 / 50%)",
            "--tw-prose-invert-th-borders": "var(--ui-text-primary)",
            "--tw-prose-invert-td-borders": "var(--ui-text-primary)",
          },
        },
      },
    },
    container: {
      center: true,
      padding: {
        DEFAULT: "1rem",
        sm: "2rem",
        lg: "3rem",
        xl: "4rem",
        "2xl": "6rem",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/typography"),
    // require("tailwindcss-radix")(),
    require('@tailwindcss/aspect-ratio'),
    require('@tailwindcss/container-queries'),
  ],
};